# Generated by Django 4.2.21 on 2025-06-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('reg_no', models.CharField(max_length=10, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
                ('year', models.CharField(choices=[('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year')], max_length=10)),
                ('gpa', models.IntegerField(default=0)),
                ('gmail_id', models.CharField(max_length=20, null=True)),
                ('photo', models.ImageField(null=True, upload_to='media/')),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
