# Generated by Django 4.2.21 on 2025-06-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_data',
            name='password',
        ),
    ]
