# Generated by Django 4.2.21 on 2025-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_user_role_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ph_no',
            field=models.IntegerField(max_length=13, null=True),
        ),
    ]
